# Generated by Django 4.1 on 2022-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_product_pr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_img',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='pr_images', verbose_name='Product Image'),
        ),
    ]
